### ISSUE TITLE
Add Gentoo ebuilds

### ISSUE THREAD

**Issue by myrvogna** [Berulacks/yams#10]
Hello,

I have been using your scrobbler for months, and liked it so much that it was one of the first packages I realised I was missing after migrating from Arch to Gentoo, so first of all: I would like to thank you for your work.

Ever since, I have been maintaining a [couple of ebuilds](https://github.com/myrvogna/myrvolay/tree/main/dev-python/yams)  in my [personal Portage overlay](https://github.com/myrvogna/myrvolay) that anyone can easily access, providing ebuilds that I believe to be of perfectly fine quality, both for the latest release and the git master branch.

I am considering the possibility of submitting them either to the main repository or to the official user repository GURU at some point in the future, although regardless in the meantime I will keep them up to date since, well, I use YAMS on an almost daily basis.

I would suggest adding them to the **Installation** section of the README if you would be so inclined, perhaps it might help a soul or two? If necessary I could make a pull request with the necessary changes, though I would also understand if you prefer to keep that section limited to generic instructions along with your own package – that would be perfectly fair!

In any case, I figured out it could not hurt to suggest it and share my appreciation of your creation~

**Comment by Berulacks** [comment]
Heya myrvogna,

Thanks for the kind words! Glad you liked the scrobbler.

Yeah, I can add a link to your ebuilds, however I will have to do so with clear indication that your repo is not managed by me and that I, as such, cannot vouch for its validity/safety any more than simply pointing out it exists. 

...Not that I don't trust you, but this is the internet - it makes sense to tread carefully. I'm hoping Gentoo users would be responsible enough to manually go over the source of any custom user packages they compile/install, anyway.

**Comment by myrvogna** [comment]
That's a perfectly reasonable course of action and the way I would have done it myself, thank you!
