### ISSUE TITLE
Update Gentoo ebuild location

### ISSUE THREAD

**Issue by myrvogna** [Berulacks/yams#11]
Hello again,

A quick follow‑up to #10, I have contributed the ebuilds to the official Gentoo User Repository [GURU](https://wiki.gentoo.org/wiki/Project:GURU) and will continue to maintain it there in the future, so it'll be nice to update the link to it. Of course, the same sensible warning still applies, but it should nonetheless be more easily accessible and owing to the nature of the GURU project, somewhat more trustworthy.

Thank you.

**Comment by Berulacks** [comment]
Cheers, I've updated the link!
