### ISSUE TITLE
Any interest in scrobble as album artist?

### ISSUE THREAD

**Issue by bndlfm** [Berulacks/yams#12]
If I wrote a pull request to add a config option to scrobble album artists as artists would you be interested?

If not I'll just do it the dirty way.

If you're wondering why someone would want this I use Musicbrainz Picard to tag all my music and organize my library. Quite often whoever added the album to their database puts the features in the artist tag.

**Comment by Berulacks** [comment]
Yep, I'd be interested. I too use album artists, as my library is managed by beets. However, I've never really thought about the difference in scrobbles. 

If you send a pull request I'd be more than happy to review it. 

Edit: Sorry for the late response, has been a busy week.

**Comment by bndlfm** [comment]
I apologize I kind of forgot about this and am not on git much. I'll try and get some done this weekend.
