### ISSUE TITLE
Outdated Pip installation package

### ISSUE THREAD

**Issue by Alejandro-Roldan** [Berulacks/yams#14]
I dont know if here is the best place to report this so let me know.

The pip package installation seems to be out of order. Having V0.69 (haha nice) as the most recent, but having newer versions listed [https://pypi.org/project/YAMScrobbler/#history](https://pypi.org/project/YAMScrobbler/#history) which do indeed have a proper date.

I reckon it has to do with the second dot in 0.7.3 vs 0.69 , so it considers 69 to be newer (?)

This creates an issue with upgrading to python 3.10 because in that yams version the requirements version are specified with == , and the mpd2 specified version is not compatible with python3.10

```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/yams/__main__.py", line 1, in <module>
    from yams.scrobble import cli_run
  File "/usr/lib/python3.10/site-packages/yams/scrobble.py", line 5, in <module>
    from mpd import MPDClient
  File "/home/leptope/.local/lib/python3.10/site-packages/mpd/__init__.py", line 20, in <module>
    from mpd.base import CommandError
  File "/home/leptope/.local/lib/python3.10/site-packages/mpd/base.py", line 20, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

Thanks for all the work too :)

**Comment by Berulacks** [comment]
Oh wow, good catch. Been using the aur packages myself, hadn't noticed that discrepancy!

I'll do a version bump and update the requirements.txt when I get the chance later today, need to add something anyway. 

Thanks for letting me know!

**Comment by Alejandro-Roldan** [comment]
Could you notify me when you bump it please? :D

**Comment by Berulacks** [comment]
@Alejandro-Roldan Of course

**Comment by volteret4** [comment]
Is this fixed? I am getting the same error now.
Thanks for your work!!

**Comment by Berulacks** [comment]
Oh my god, I totally forgot to do this. Forgive me, folks.

I've fixed the issue by removing the previous versions from pip - `0.7.3` is the latest version.
