### ISSUE TITLE
Keep .lastfm _session out of config directory

### ISSUE THREAD

**Issue by Thaodan** [Berulacks/yams#17]
Hey, 

I would be nice if the authentication token would be keep out of the configuration directory to not accidentally expose it.
Maybe XDG_STATE_HOME would fit:
https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html

**Comment by Berulacks** [comment]
Sorry for the late response - been away from this project a bit, and I definitely need to get to the three outstanding issues. 

Thanks for the recommendation. One of the issues is to add XDG directories support; this can be included as a part of that.
