### ISSUE TITLE
PID file remains after yams is killed

### ISSUE THREAD

**Issue by YodaEmbedding** [Berulacks/yams#4]
If I kill YAMS, then the PID file remains. There are some problems associated with this. Consider the scenario:

> The user inadvertently kills yams (e.g. by rebooting).  
> The user encounters the error `YAMS is already running, kill it before running again!`.  
> The user runs `yams --kill-daemon`.  
> This kills a non-YAMS process!
> (In my case, I got lucky because I believe YAMS was trying to kill a process it didn't have permissions to kill. Then, I investigated why YAMS was refusing to start after trying to run it manually.)

There should be some sort of check that YAMS is killing *only* a YAMS process. Perhaps check the path and arguments passed to it? For instance,

    $ PID=$(cat ~/.config/yams/yams.pid)
    $ cat "/proc/$PID/cmdline" | sed -e "s/\x00/ /g"; echo
    python -m yams -N

*And Another Thing...* you can use the [`tempfile`](https://docs.python.org/3/library/tempfile.html) module to ensure that the file you create truly is temporary. (e.g. for Linux, it gets stored in `/tmp`.)

**Comment by Berulacks** [comment]
That's a great point. Normally the pid file is supposed to be cleaned up during a graceful shutdown, but in any other scenario it could be quite problematic if it's left behind. 

tempfile could work, I'm going to look into that. Thanks for bringing this to my attention!

**Comment by YodaEmbedding** [comment]
I think it might still be a good idea to verify the process path/arguments since [PIDs can be reused](https://unix.stackexchange.com/questions/414971/pid-reuse-possibility-in-linux). (e.g. If yams is killed and another process spawns before yams is restarted.)

**Comment by Berulacks** [comment]
I generally prefer not to make platform specific changes (when possible - the whole `--attach` functionality being an alias for `tail -F` was hacky and terrible, but convenient :) ). 

I'm thinking if the temporary file is only kept while the program is running, then it can be useful to use that (+ a cache file pointing to it) to track the PID - this is assuming the temp file is removed even on crash. If not, maybe something like a socket through which messages can be passed might be cleanest - but that, too, isn't platform agnostic :thinking: 

Anyway, I'll update when I implement something passable.

**Comment by Berulacks** [comment]
Closed in the last commit - feel free to try it out and let me know how it goes! Things have changed quite a bit in the new release, so test via `pip install -e --user /path/to/the/yams/repo` locally (if you're so inclined)
