### ISSUE TITLE
Error trying to scrobble to libre.fm

### ISSUE THREAD

**Issue by fritz-k** [Berulacks/yams#7]
I installed the current python-yams package from the AUR and set it up for libre.fm according to the docs.

Every time I run yams, I get the error
```python
2020-06-20 12:01:05,204 - yams - DEBUG - Making request to 'https://libre.fm/2.0':
'{'method': 'track.updateNowPlaying', 'artist': 'Fleetwood Mac', 'track': 'Oh Daddy', 'context': 'mpd', 'api_key': 'redacted_key', 'sk': 'redacted_sk', 'album': 'Rumours', 'trackNumber': '10', 'duration': '233.116', 'api_sig': 'redacted_sig'}'
2020-06-20 12:01:06,030 - yams - DEBUG - Response: <?xml version="1.0"?>
<lfm status="failed">
  <error code="3">Invalid Method - No method with that name in this package</error>
</lfm>

2020-06-20 12:01:06,032 - yams - INFO - Now playing was a success!
[...]
2020-06-20 12:02:58,290 - yams - DEBUG - Making request to 'https://libre.fm/2.0':
'{'method': 'track.scrobble', 'artist': 'Fleetwood Mac', 'timestamp': 1592647265.2020864, 'track': 'Oh Daddy', 'api_key': 'redacted_key', 'sk': 'redacted_sk', 'album': 'Rumours', 'trackNumber': '10', 'duration': '233.116', 'api_sig': 'redacted_sig'}'
2020-06-20 12:02:59,143 - yams - DEBUG - Response: <?xml version="1.0"?>
<lfm status="failed">
  <error code="3">Invalid Method - No method with that name in this package</error>
</lfm>

2020-06-20 12:02:59,144 - yams - ERROR - Something went very wrong!
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/yams/scrobble.py", line 1008, in cli_run
    mpd_watch_track(client, session, config)
  File "/usr/lib/python3.8/site-packages/yams/scrobble.py", line 806, in mpd_watch_track
    scrobble_succeeded = scrobble_track(
  File "/usr/lib/python3.8/site-packages/yams/scrobble.py", line 518, in scrobble_track
    "Scrobbles accepted: {}".format(xml.find("scrobbles").get("accepted"))
AttributeError: 'NoneType' object has no attribute 'get'
2020-06-20 12:02:59,145 - yams - INFO - Shutting down...
```

I tried calling the api manually with the parameters from yams:
`https://libre.fm/2.0/?method=track.updateNowPlaying&artist=Fleetwood%20Mac&track=Never%20Going%20Back%20Again&context=mpd&api_key=redacted_key&sk=redacted_sk&album=Rumours&trackNumber=3&duration=134.243&api_sig=redacted_sig`
(different song, but shouldn't matter) which returns a different error:

```xml
<lfm status="failed">
  <error code="6">Invalid parameters - Your request is missing a required parameter</error>
</lfm>
```

**Comment by Berulacks** [comment]
Hey fritz, can you post your config (with api-keys redacted)?

**Comment by fritz-k** [comment]
```yaml
allow_same_track_scrobble_in_a_row: false
api_key: redacted_key
api_secret: redacted_secret
base_url:  https://libre.fm/2.0
disable_log: false
mpd_host: 127.0.0.1
mpd_port: '6600'
no_daemon: false
real_time: true
scrobble_min_time: 10
scrobble_threshold: 50
session_file: /home/local-username/.config/yams/.lastfm_session
update_interval: 1
watch_threshold: 5
```

**Comment by Berulacks** [comment]
Hmm... comparing my libre.fm-using-YAMS config to yours there aren't any significant differences, and things are working fine on this end. ~~Have you confirmed that your api_key and api_secret work with Libre.Fm in other clients? (assuming they're not the default yams values)~~

~~Could you delete your session file at `/home/local-username/.config/yams/.lastfm_session` then also comment out your `api_key` and `api_secret` in the config? This will ensure you're using the default yams api key and secret, which I know work fine on LibreFM - though IIRC any key and secret should technically work. After that you can try to re-authenticate (obviously replacing the `last.fm` part of the authentication url with `libre.fm` - I need to allow you to override this, or at least generate this string using the `base_url` somehow 🤔 )~~

Update: I've reproduced the bug on my end, I'm looking into it.

**Comment by Berulacks** [comment]
> I tried calling the api manually with the parameters from yams:
https://libre.fm/2.0/?method=track.updateNowPlaying&artist=Fleetwood%20Mac&track=Never%20Going%20Back%20Again&context=mpd&api_key=redacted_key&sk=redacted_sk&album=Rumours&trackNumber=3&duration=134.243&api_sig=redacted_sig
(different song, but shouldn't matter) which returns a different error: (...)

This might not work as you need to [sign](https://www.last.fm/api/authspec) your request - each signature being unique to each request if any of the request parameters differ (could apply to `duration`?) (this on the Last.FM API, of course - however I have no reason to believe Libre.FM doesn't use this system either)

**Comment by Berulacks** [comment]
Oh crap, okay so it seems the 
```<lfm status="failed">
  <error code="3">Invalid Method - No method with that name in this package</error>
</lfm>
```

response to `updateNowPlaying` is to be accepted as Libre.FM doesn't support "now playing". I'm going to add a check for that which will disable now playing requests for Libre.FM (though those errors are harmless on our end)

**Comment by fritz-k** [comment]
Thanks for looking into this issue. Is `track.scrobble` also not implemented? In the log I posted, both these apis produced this kind of error.

**Comment by Berulacks** [comment]
So, after fucking around with my local installation trying to reproduce the bug I now get it consistently :D Have no idea why it started happening and I literally have my last successful scrobble to Libre.FM from 8 minutes ago.

So, `track.scrobble` has been working fine for months - but now suddenly it's not? 😅 Clearly something is awry, here... I would have thought it was an issue on YAMS' end but I've got months worth of scrobbles from YAMS/mpd so clearly something I did (and presumably, at some point in time, you as well) broke it.

I'm investigating, but I might not have time to do a proper deep dive into the issue until later in the day.

**Comment by Berulacks** [comment]
> Thanks for looking into this issue. Is track.scrobble also not implemented? In the log I posted, both these apis produced this kind of error.

Should be, or else it's impossible for us to scrobble. `nowPlaying` definitely isn't, though

**Comment by Berulacks** [comment]
I- What? A `nowPlaying` call just went through correctly? ...and the scrobble worked just fine? 

```
2020-06-22 10:29:23,060 - yams - DEBUG - Making request to 'https://libre.fm/2.0/':
'{'method': 'track.scrobble', 'artist': 'Woob', 'timestamp': 1592810921.634115, 'track': 'A1 Novak 監視™', 'api_key': 'xxx', 'sk': 'xxx', 'album': 'Tokyo Substrate Paradox', 'trackNumber': '1', 'duration': '81.952', 'api_sig': 'xxx'}'
2020-06-22 10:29:24,757 - yams - DEBUG - Response: <?xml version="1.0"?>
<lfm status="ok">
  <scrobbles accepted="1" ignored="0">
    <scrobble>
      <track corrected="0">A1 Novak &#x76E3;&#x8996;&#x2122;</track>
      <artist corrected="0">Woob</artist>
      <album corrected="0">Tokyo Substrate Paradox</album>
      <albumArtist corrected="0"/>
      <timestamp>1592810921</timestamp>
      <ignoredMessage code="0"/>
    </scrobble>
  </scrobbles>
</lfm>

2020-06-22 10:29:24,757 - yams - INFO - Scrobbles accepted: 1
2020-06-22 10:29:24,757 - yams - INFO - Scrobbling was a success!
2020-06-22 10:29:24,757 - yams - DEBUG - XML Received for scrobble: <lfm status="ok">
```

**Comment by Berulacks** [comment]
@fritz-k Can you try setting the `base_url` to `https://libre.fm/2.0/` with the trailing slash? That seemed to work - scrobbling with libre.fm is currently working again on my end:

![image](https://user-images.githubusercontent.com/4644265/85260608-9f980400-b473-11ea-8ba4-8422a07d4248.png)

Edit: Either way, I'm going to update YAMS to not crash when the response is a valid XML but contains `status=failed` - that's a pretty big bug on our end.

**Comment by fritz-k** [comment]
> @fritz-k Can you try setting the `base_url` to `https://libre.fm/2.0/` with the trailing slash? That seemed to work - scrobbling with libre.fm is currently working again on my end:

Same here. The trailing slash did the trick! Thanks a lot for helping out so quickly :)

> Edit: Either way, I'm going to update YAMS to not crash when the response is a valid XML but contains `status=failed` - that's a pretty big bug on our end.

Best also add the trailing slash to the readme and emphasize on its importance ^^
