### ISSUE TITLE
Unsharable config files

### ISSUE THREAD

**Issue by bbaserdem** [Berulacks/yams#9]
First of all; great work. I'm loving this scrobbler.

I put my configuration files on version control and put them on github (along many other linux users) and it is generally expected that the files in `~/.config` (should be `$XDG_CONFIG_HOME`) do not contain any sensitive information, and are static.

For logs, runtime files and cache files; there is `$XDG_DATA_HOME` (usually `~/.local/share`) and `$XDG_CACHE_HOME` (usually `~/.local/share`)

The session file location can be customized in the config; but is there a way to move the `api_key` and `api_secret` to another file than the config one?

**Comment by Berulacks** [comment]
>  it is generally expected that the files in ~/.config (should be $XDG_CONFIG_HOME) do not contain any sensitive information, and are static.
> For logs, runtime files and cache files; there is $XDG_DATA_HOME (usually ~/.local/share) and $XDG_CACHE_HOME (usually ~/.local/share)

Yes, I absolutely agree. I was a bit lazy when writing the configuration scripts and just defaulted to dropping things into `~/.config`. In the coming days I'll update the script to honor any `$XDG_(...)` environment vars that are present when configuring for the first time - though if none are present I will still default to `~/.config` as I (personally) dislike separating log and cache files. 

> The session file location can be customized in the config; but is there a way to move the api_key and api_secret to another file than the config one?

These keys are hard-coded in the source and belong to the "YAMS" Last.FM program tied to my account. Without these you wouldn't be able to simply install and run the program, but would need to log into your account and create your own developer keys. If you've chosen to do this for your account, I can add a configuration option for loading a supplemental config? E.g. `additional_config = /path/to/your/secret/stuff` which could be loaded on top of the current config, allowing you to only sync the main config to github. Does that work? 

Also, as far as I'm aware the only _default_ account-sensitive information is the session key, which is always read in from its own file, and can be placed anywhere.

**Comment by bbaserdem** [comment]
Oh the keys are NOT associated with my private account; it's to do with the API connection. And the `.lastfm_session` is my login info. This was a misunderstanding in my part. 

>  can add a configuration option for loading a supplemental config?

That would be a good thing. But now that i resolved my misunderstanding; I have no issue with the current config options. (I can point the appropriate files to their appropriate directories myself; that should be no problem. Though the first config generation picking the environment variables up would be neat.)

I don't know if I should leave this issue open or closed; so feel free to take any action.

**Comment by Berulacks** [comment]
> I don't know if I should leave this issue open or closed; so feel free to take any action.

I'll keep it open so it bothers me into adding support for the `XDG_(...)` environment vars. (been a busy week and a half, will get to it eventually)

Most likely won't do the supplemental config loading at this point, perhaps maybe later.

**Comment by Berulacks** [comment]
Closed with https://github.com/Berulacks/yams/commit/9cf80910222a0a467267cb1369f01f0bbc9d7809

**Comment by Berulacks** [comment]
Closed with https://github.com/Berulacks/yams/commit/9cf80910222a0a467267cb1369f01f0bbc9d7809
